/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export const TITLE_PART_1 = [
  "Abounding",
  "Accomplished",
  "Accurate",
  "Active",
  "Adolescent",
  "Aggressive",
  "Always-On",
  "Ancient",
  "Animal",
  "Anonymous",
  "Apprentice",
  "Aquatic",
  "Aromatic",
  "Art-School",
  "Aspiring",
  "Assumed",
  "At-Capacity",
  "Atmospheric",
  "Autonomous",
  "Avaricious",
  "Bait-Snatching",
  "Basement",
  "Battle-Tested",
  "Bodyboardin'",
  "Bold",
  "Bona Fide",
  "Buried",
  "Caffeinated",
  "Carefree",
  "Careful",
  "Caretaking",
  "Casual",
  "Catchable",
  "Celebratory",
  "Cerulean",
  "Change-It-Up",
  "Chaotic",
  "City Folk",
  "Clever",
  "Cliffhanging",
  "Cold-Sensitive",
  "Comparative",
  "Competent",
  "Complete",
  "Connected",
  "Cool",
  "Countdown",
  "Covert",
  "Covetous",
  "Cowardly",
  "Crafty",
  "Creative",
  "Crisp",
  "Crop-tending",
  "Curious",
  "Dad-Joking",
  "Deadline",
  "Deep-Sea",
  "Defiant",
  "Deserted-Island",
  "Destructive-Creative",
  "Detail-Oriented",
  "Detailed",
  "Digital-Age",
  "Discerning",
  "Disconnected",
  "Discovered",
  "Distinctive",
  "Down-And-Out",
  "Dreamy",
  "Easy-Breezy",
  "Eco-Friendly",
  "Efficient",
  "Elusive",
  "Emergent",
  "Emerging",
  "Energetic",
  "Evolving",
  "Exalted",
  "Factual",
  "Fall-Born",
  "Farming",
  "Fastidious",
  "Festive",
  "Fickle",
  "Field-Fresh",
  "Fierce",
  "Flapping",
  "Flightless",
  "Flower-Loving",
  "Flying",
  "Foolhardy",
  "Fragrant",
  "Fresh",
  "Freshly Delivered",
  "Friendly",
  "Friendship",
  "Full-Fledged",
  "Future",
  "Generous",
  "Glittering",
  "Global",
  "Gorgeous",
  "Greedy",
  "Green-Thumbed",
  "Greenhouse",
  "Growing",
  "Grown",
  "Handmade",
  "Happy",
  "Happy Home",
  "Hardworking",
  "Hay-Feverish",
  "Heavenly",
  "Herbivorous",
  "Highly Aware",
  "Hip",
  "Historic",
  "History-Loving",
  "Hobby-Level",
  "Home",
  "Homey",
  "Hooked",
  "Hospitable",
  "Household",
  "Humbly Begun",
  "Humming",
  "Hungry",
  "Impressive",
  "Individual",
  "Inexperienced",
  "Inspirational",
  "Interior",
  "Internet",
  "Invested",
  "Invulnerable",
  "Jovial",
  "Kind",
  "Kindly",
  "Knowledge-Thirsty",
  "Late-Night",
  "Legendary",
  "Liberal-Arts",
  "Locally Sourced",
  "Lonely",
  "Longtime",
  "Lucky",
  "Ludicrously Popular",
  "Materialistic",
  "Mature",
  "Messy",
  "Midsummer",
  "Mistakenly Caught",
  "Moderate",
  "Mold-Breaking",
  "Name-Dropping",
  "Natural",
  "New-Leaf",
  "Nicknamed",
  "Night-Owl",
  "Nook Inc.'s",
  "Novel",
  "Novice",
  "Nurturing",
  "Occasional",
  "Oceanic",
  "Off-Season",
  "Omnivorous",
  "One-Room",
  "Organic",
  "Outdoor-Loving",
  "Outdoorsy",
  "Over-Shelled",
  "Overacting",
  "Overboard",
  "Overnight",
  "Overstuffed",
  "Partially Obscured",
  "Peak-performing",
  "Peppy",
  "Perennial",
  "Perfectionist",
  "Photogenic",
  "Picky",
  "Plausible",
  "Plaza",
  "Plucky",
  "Pocket",
  "Pointy",
  "Pole-Fishing",
  "Polymorphing",
  "Pond-Raised",
  "Precocious",
  "Pro",
  "Productive",
  "Quintessential",
  "Radiant",
  "Rain-soaked",
  "Rare",
  "Rascally",
  "Ready",
  "Ready-Made",
  "Rebellious",
  "Refined",
  "Regular",
  "Relentless",
  "Reliable",
  "Remodeling",
  "Respected",
  "Responsible",
  "Restless",
  "Rich",
  "Risen",
  "Rotten",
  "Rough-And-Tumble",
  "Rowdy",
  "Royal",
  "Rumormongering",
  "Savvy",
  "Scarce",
  "Science-y",
  "Seashore",
  "Seaside",
  "Seasonal",
  "Second-Floor",
  "Self-Paced",
  "Self-Possessed",
  "Shady",
  "Sharp",
  "Shell-Grabbing",
  "Shell-Less",
  "Shellfish",
  "Shifty",
  "Shining",
  "Single-Occupant",
  "Sleepless",
  "Small-Fry",
  "Smartphone",
  "Snow",
  "So-Called",
  "Soaring",
  "Solitary",
  "Solo",
  "Soothing",
  "Specific",
  "Spirited",
  "Splashy",
  "Sports-Minded",
  "Sporty",
  "Spring-Born",
  "Standoffish",
  "Status-Minded",
  "Stoic",
  "Subculture",
  "Summer-Born",
  "Sun-Kissed",
  "Super-Popular",
  "Supernatural",
  "Surfing",
  "Surprising",
  "Sustainable",
  "Sweet-Smelling",
  "Swept-Away",
  "Teary-Eyed",
  "Tentative",
  "The Definition of",
  "Thorny",
  "Thrifty",
  "Thriving",
  "Tidal",
  "Tidy",
  "Top-Notch",
  "Total",
  "Trailblazing",
  "Trapped",
  "Traveling",
  "Trendy",
  "Trivia",
  "Tropically Grown",
  "Twin's",
  "Ultimate",
  "Unabashedly",
  "Understated",
  "Unhindered",
  "Unique",
  "Unpearable",
  "Unrestrained",
  "Untamed",
  "Untossable",
  "Upstart",
  "Verdant",
  "Very First",
  "Vibrant",
  "Vigorous",
  "Voyaging",
  "Wasteful",
  "Water's Edge",
  "Waterlogged",
  "Waterway",
  "Wave-Tossed",
  "Weak",
  "Weekend",
  "Well-Known",
  "Whimsical",
  "Wide-Ranging",
  "Widely Accepted",
  "Wild",
  "Wild World",
  "Wild-Child",
  "Winter-Born",
  "Wishful",
  "Worldwide",
  "Year-Round"
];

export const TITLE_PART_2 = [
  "\"It\" Girl",
  "\"It\" Guy",
  "Adult",
  "Adventurer",
  "Aficionado",
  "Ally",
  "Angel",
  "Angler",
  "Ant",
  "Appliance Fan",
  "Artisan",
  "Artist",
  "Artistic Statement",
  "Athlete",
  "Authority",
  "Avatar",
  "Baby",
  "Backbone",
  "Barista",
  "Beach Bum",
  "Beachcomber",
  "Beans",
  "Beast",
  "Beginner",
  "Being",
  "Bellionaire",
  "Bigwig",
  "Bill Payer",
  "Birthday Boy",
  "Birthday Girl",
  "Blend",
  "Blossom",
  "Boater",
  "Bodybuilder",
  "Boss",
  "Bounty",
  "Boy",
  "Break",
  "Bride",
  "Brute",
  "Buddy",
  "Butterfly",
  "Camper",
  "Caretaker",
  "Catch of the Day",
  "Celebrity",
  "Challenger",
  "Character",
  "Child",
  "Chill Soul",
  "Chiller",
  "Chum",
  "Cleaner",
  "Clown",
  "Club Member",
  "Coast Dweller",
  "Coconut",
  "Collector",
  "Comedian",
  "Connector",
  "Consumer",
  "Coordinator",
  "Crafter",
  "Creator",
  "Critter",
  "crops",
  "Crusher",
  "Curator",
  "Custodian",
  "Cynic",
  "Dancer",
  "Darling",
  "Daughter",
  "Days",
  "Deadeye",
  "Decorating Fiend",
  "Defender",
  "Denizen",
  "Designer",
  "Dietitian",
  "Discovery",
  "Diver",
  "Dreamer",
  "Dynamo",
  "Eccentric",
  "Ecologist",
  "Egg",
  "Emperor",
  "Empress",
  "Engineer",
  "Enthusiast",
  "Eventuality",
  "Existentialist",
  "Expert",
  "Explorer",
  "Fake",
  "Family",
  "Family Member",
  "Fan",
  "Father",
  "Fertilizer",
  "Figure",
  "Fish",
  "Fisher",
  "Fishing Fan",
  "Fitness Fan",
  "Fixer",
  "Flag Waver",
  "Floaty Thing",
  "Flower",
  "Follower",
  "Force",
  "Fossil",
  "Fowl",
  "Free Spirit",
  "Free-Wheeler",
  "Frenzy",
  "Freshman",
  "Friend",
  "Gamer",
  "Gardener",
  "Genius",
  "Ghost",
  "Gifted One",
  "Girl",
  "Go-Getter",
  "Grandma",
  "Grandpa",
  "Greenhorn",
  "Groom",
  "Ground Traveler",
  "Grub",
  "Guard",
  "Gyroid",
  "Health Nut",
  "Heart Stealer",
  "Hero",
  "Heroine",
  "Hobbyist",
  "Honey",
  "Hunter",
  "Imp",
  "Individual",
  "Influencer",
  "Ingredient",
  "Insect",
  "Inspiration",
  "Intellectual",
  "Interior-Design Fan",
  "Island Dweller",
  "Island Resident",
  "Jetsam",
  "Jewel",
  "Keeper",
  "Kid",
  "Kind",
  "King",
  "Klutz",
  "Lad",
  "Landlord",
  "Lass",
  "Lawn Clippings",
  "Legend",
  "Life",
  "Life Hacker",
  "Life-Form",
  "Lone Wolf",
  "Loner",
  "Lost One",
  "Luminary",
  "Ma",
  "Mama",
  "Manager",
  "Master",
  "Materialist",
  "Matriarch",
  "Meanie",
  "Mega Star",
  "Meister",
  "Mermaid",
  "Merrymaker",
  "Metamorphosis",
  "Meteorite",
  "Migratory Bird",
  "Miracle",
  "Modder",
  "Model",
  "Moneybags",
  "Monster",
  "Mother",
  "Mr. Popular",
  "Ms. Popular",
  "Muscle",
  "Musician",
  "MVP",
  "Neatnik",
  "Neophyte",
  "Observationist",
  "Older Brother",
  "Older Sister",
  "One",
  "Other Half",
  "Outlaw",
  "Overachiever",
  "Overheater",
  "Pa",
  "Pal",
  "Papa",
  "Paradise",
  "Parent",
  "Partier",
  "Partitioner",
  "Party Animal",
  "Patron",
  "Pear",
  "Person",
  "Personality",
  "Pesca Pro",
  "Pet",
  "Philosopher",
  "Photographer",
  "Pioneer",
  "Poet",
  "Pop Star",
  "Populace",
  "Prince",
  "Princess",
  "Problem Solver",
  "Prodigy",
  "Producer",
  "Provider",
  "Punk",
  "Pupa",
  "Queen",
  "Reaction",
  "Rebel",
  "Reckless One",
  "Regular",
  "Rejuvenator",
  "Relocator",
  "Remodeler",
  "Representative",
  "Researcher",
  "Resident",
  "Reviewer",
  "Ringleader",
  "Rookie",
  "Rose",
  "Ruiner",
  "Runner",
  "Savant",
  "Savior",
  "Scatterbrain",
  "Scent",
  "Seashell Seller",
  "Season",
  "Seaweed",
  "Seeker",
  "Seller",
  "Semiprofessional",
  "Sentiment",
  "Sentinel",
  "Shell Fan",
  "Shell Master",
  "Shellaborator",
  "Shellarina",
  "Shellector",
  "Shopaholic",
  "Shy Kid",
  "Sidekick",
  "Slingshot Ace",
  "Snake",
  "Sneezer",
  "Soil",
  "Something Or Other",
  "Son",
  "Sort",
  "Sorter",
  "Soul",
  "Soul Mate",
  "Space",
  "Specialist",
  "Speculator",
  "Sprite",
  "Sprout",
  "Stalkholder",
  "Standard",
  "Star",
  "Start",
  "Statement",
  "Statue",
  "Student",
  "Stylist",
  "Success",
  "Sundries Fan",
  "Superhero",
  "Supervisor",
  "Supporter",
  "Supreme Being",
  "Surfer",
  "Symbol",
  "Tack",
  "Talent",
  "Technician",
  "Tourist",
  "Trader",
  "Transformer",
  "Trash",
  "Traveler",
  "Tree",
  "Troublemaker",
  "Truth",
  "Type",
  "Vagabond",
  "VIP",
  "Virtuoso",
  "Walking Dictionary",
  "Wallflower",
  "Wanderer",
  "Wild Child",
  "Winner",
  "Wonder",
  "Worrywart",
  "Writer",
  "Young'un",
  "Younger Brother",
  "Younger Sister",
  "Youngster",
  "Youth"
];

export const AVATAR_ICONS = [
  { char: "🦤", label: "Dodo" },
  { char: "🍑", label: "Peach" },
  { char: "💰", label: "Bell Bag" },
  { char: "🦖", label: "Fossil" },
  { char: "🌠", label: "Star" },
  { char: "🍃", label: "Leaf" },
  { char: "🍎", label: "Apple" },
  { char: "🌴", label: "Palm Tree" },
  { char: "🎁", label: "Present" },
  { char: "🦋", label: "Butterfly" },
  { char: "🎣", label: "Fishing Rod" },
  { char: "⛺", label: "Tent" },
  { char: "🧸", label: "Plushie" },
  { char: "🦉", label: "Owl" },
  { char: "🍊", label: "Orange" }
];

export const PASSPORT_COLORS = [
  { bg: 'bg-[#FF9A9E]/20', border: 'border-[#FF9A9E]/40', dot: 'bg-[#FF9A9E]', text: 'text-[#FF9A9E]', name: 'Coral Pink' },
  { bg: 'bg-[#A1C4FD]/20', border: 'border-[#A1C4FD]/40', dot: 'bg-[#A1C4FD]', text: 'text-[#A1C4FD]', name: 'Seafoam Blue' },
  { bg: 'bg-[#D4FC79]/20', border: 'border-[#D4FC79]/40', dot: 'bg-[#D4FC79]', text: 'text-[#D4FC79]', name: 'Nook Green' },
  { bg: 'bg-[#FAD0C4]/20', border: 'border-[#FAD0C4]/40', dot: 'bg-[#FAD0C4]', text: 'text-[#FAD0C4]', name: 'Sunset Orange' },
  { bg: 'bg-[#E2D1F9]/20', border: 'border-[#E2D1F9]/40', dot: 'bg-[#E2D1F9]', text: 'text-[#E2D1F9]', name: 'Lavender Mist' }
];

export const PLANE_COLORS = [
  { id: 'orange', name: 'Orange Seaplane', hex: '#FF9F43', bg: 'bg-[#FF9F43]', border: 'border-[#E27A14]', text: 'text-[#FF9F43]' },
  { id: 'blue', name: 'Blue Seaplane', hex: '#0084CC', bg: 'bg-[#0084CC]', border: 'border-[#00659C]', text: 'text-[#0084CC]' },
  { id: 'green', name: 'Green Seaplane', hex: '#2ECC71', bg: 'bg-[#2ECC71]', border: 'border-[#229B53]', text: 'text-[#2ECC71]' },
  { id: 'yellow', name: 'Yellow Seaplane', hex: '#F1C40F', bg: 'bg-[#F1C40F]', border: 'border-[#BCA110]', text: 'text-[#F1C40F]' }
] as const;

export const GATE_THEMES: Record<number, { name: string; icon: string; desc: string; color: string; bg: string; text: string; tag: string }> = {
  1: { name: "Nook's Trading Post", icon: "💰", desc: "Optimal for Turnip Sellers, trading items/Bells, and cataloging items.", color: "#0084CC", bg: "bg-sky-50", text: "text-[#0084CC]", tag: "SKY-1" },
  2: { name: "Meteor Observatory", icon: "🌠", desc: "Optimal for meteor showers, Celeste stargazing, and space DIY hunting.", color: "#FF9F43", bg: "bg-orange-50", text: "text-[#FF9F43]", tag: "STAR-2" },
  3: { name: "Flick & C.J. Safari", icon: "🦋", desc: "Optimal for premium Bug Catching, Fishing tourneys, and bug swaps.", color: "#E05252", bg: "bg-red-50", text: "text-[#E05252]", tag: "BUG-3" },
  4: { name: "Island Explorers", icon: "🏝️", desc: "Optimal for sightseeing, shopping, fruit picking, and custom tours.", color: "#2ECC71", bg: "bg-emerald-50", text: "text-[#2ECC71]", tag: "COAST-4" },
  5: { name: "DIY & Freebie Lounge", icon: "🎁", desc: "Optimal for recipe card swaps, clothing giveaways, and item recycling.", color: "#9B59B6", bg: "bg-purple-50", text: "text-[#9B59B6]", tag: "LOBBY-5" }
};

export const DREAM_THEMES: Record<number, { name: string; icon: string; desc: string; color: string; bg: string; text: string; tag: string }> = {
  1: { name: "Cottagecore / Fairycore", icon: "🍄", desc: "Aesthetic forests, mushrooms, and whimsical nature vibes.", color: "#8B5A2B", bg: "bg-amber-50", text: "text-[#8B5A2B]", tag: "NATURE-1" },
  2: { name: "Horror / Spooky", icon: "👻", desc: "Haunted towns, creepy stories, and scary island themes.", color: "#4B0082", bg: "bg-purple-50", text: "text-[#4B0082]", tag: "SPOOKY-2" },
  3: { name: "Urban / Citycore", icon: "🏙️", desc: "Bustling streets, crosswalks, shops, and dense city living.", color: "#555555", bg: "bg-gray-50", text: "text-[#555555]", tag: "CITY-3" },
  4: { name: "Tropical Resort", icon: "🏖️", desc: "Relaxing beaches, tiki bars, pools, and island getaways.", color: "#00CED1", bg: "bg-cyan-50", text: "text-[#00CED1]", tag: "RESORT-4" },
  5: { name: "Interactive Puzzle", icon: "🧩", desc: "Maze runs, mysteries, scavenger hunts, and lore islands.", color: "#FF4500", bg: "bg-orange-50", text: "text-[#FF4500]", tag: "PUZZLE-5" }
};

export interface StampChallenge {
  id: string;
  title: string;
  desc: string;
  miles: number;
  condition: string;
  icon: string;
}

export const STAMP_CHALLENGES: StampChallenge[] = [
  { id: 'create', title: 'Frequent Flyer Stamp', desc: 'Complete and print your official Dodo Airlines Passport', miles: 500, condition: 'Print Passport', icon: '✈️' },
  { id: 'board', title: 'Island Hopper Journey', desc: 'Board any active seaplane flight and travel overseas', miles: 1000, condition: 'Board 1 flight', icon: '🏝️' },
  { id: 'host', title: 'Island Sponsor Hospitality', desc: 'Open your airport gate and list an active flight plan', miles: 1500, condition: 'Host 1 flight', icon: '🏡' },
  { id: 'chat', title: 'Tower Airwaves Chatterbox', desc: 'Broadcast a message over the airport terminal radio', miles: 300, condition: 'Send 1 radio dispatch', icon: '📻' },
  { id: 'custom', title: 'Passport Customizer Extra', desc: 'Update your passport signature or portrait photo', miles: 200, condition: 'Customize signature/avatar', icon: '🎨' },
  { id: 'standby', title: 'Lounge Standby Seeker', desc: 'Register a standby passenger request in the lounge', miles: 500, condition: 'File 1 standby request', icon: '🛋️' }
];

export const generateRandomFriendCode = (): string => {
  const chars = ['X', '0'];
  const segment = () => Array.from({ length: 4 }, () => chars[Math.floor(Math.random() * chars.length)]).join('');
  return `SW-${segment()}-${segment()}-${segment()}`;
};
